name: StubJars build
run-name: ${{ github.actor }} is testing code 🚀
on:
  - push
jobs:
  test_stubjars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        architecture: x64
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.1.0
    - name: Build the code
      uses: gradle/gradle-build-action@v2.9.0
      with:
        arguments: assemble
    - name: Run the test suite
      uses: gradle/gradle-build-action@v2.9.0
      with:
        arguments: test

